Repository Hipspot/hipspot-web, pull requests merged in 2023-01, with the labels that each got.

#3 Feat: eslint, babel 설정, test환경 설정, readme 수정, license, github config
  .eslintignore
  .eslintrc
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  README.md
  babel.config.js
  config-overrides.js
  jest.setup.js
  package.json
  pnpm-lock.yaml
  src/App.test.tsx
  src/App.tsx
  src/components/Counter.tsx
  src/index.tsx
  src/reportWebVitals.ts
  tsconfig.json
Labels: 기능개발🔥, 문서📄

#9 Feat: 인포윈도우 업체제공사진 UI 개발 #4
  .eslintrc
  config-overrides.js
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/index.ts
  src/assets/svg/CancelIcon.svg
  src/assets/svg/ClockIcon.svg
  src/assets/svg/CopyIcon.svg
  src/assets/svg/MarkerIcon.svg
  src/assets/svg/PhoneIcon.svg
  src/components/Filtering/FilterItem.tsx
  src/components/InfoWindow/Contents/Information.tsx
  src/components/InfoWindow/Contents/Map.tsx
  src/components/InfoWindow/Contents/Photoes.tsx
  src/components/InfoWindow/Contents/Tab.tsx
  src/components/InfoWindow/Contents/Title.tsx
  src/components/InfoWindow/PopUpWindow/index.tsx
  src/components/InfoWindow/PopUpWindow/smoothMove.ts
  src/components/InfoWindow/PopUpWindow/style.ts
  src/components/InfoWindow/index.tsx
  src/constants/filterDataList.ts
  src/index.css
  src/libs/styles/color.ts
  src/libs/types/cafe.ts
  src/libs/types/filter.ts
  src/libs/types/infowindow.ts
  src/libs/types/style.ts
  src/recoil/infoWindowState.ts
  tsconfig.json
Labels: 기능개발🔥

#8 Feat: ClusterList UI 구현
  package.json
  pnpm-lock.yaml
  public/index.html
  public/mockServiceWorker.js
  src/App.tsx
  src/components/ClusterList/ClusterList.test.tsx
  src/components/ClusterList/ItemList.tsx
  src/components/ClusterList/index.tsx
  src/components/Filtering/FilterItem.tsx
  src/components/Filtering/index.tsx
  src/components/Marker/index.tsx
  src/index.css
  src/index.tsx
  src/libs/types/place.ts
  src/mocks/index.ts
  src/mocks/place/data.ts
  src/mocks/place/handler.ts
  src/mocks/place/service.ts
  src/recoil/ui.ts
Labels: 기능개발🔥

#12 11/feat PopupWindow 이벤트 핸들러 분리
  .eslintrc
  src/assets/svg/CancelIcon.png
  src/components/InfoWindow/Contents/Title.tsx
  src/components/InfoWindow/PopUpWindow/eventHandler/mouse.ts
  src/components/InfoWindow/PopUpWindow/eventHandler/touch.ts
  src/components/InfoWindow/PopUpWindow/index.tsx
  src/components/InfoWindow/PopUpWindow/utils/cancelAnimation.ts
  src/components/InfoWindow/PopUpWindow/utils/reactRefUpdate.ts
  src/components/InfoWindow/PopUpWindow/utils/smoothMove.ts
  src/constants/popUpHeights.ts
  src/libs/types/infowindow.ts
  src/recoil/infoWindowState.ts
Labels: 리팩토링🛠️

#20 Feat: 빌드 스크립트 수정 #19
  .github/workflows/BUILD.yaml
  package.json
Labels: 기능개발🔥

#18 Feat : 필터링 상태에 맞는 마커 랜더링 기능 구현
  .env
  .eslintrc
  .gitignore
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/App.tsx
  src/api/getGeoJson.ts
  src/components/Counter.tsx
  src/components/MapComp/index.tsx
  src/components/MapComp/utils/mapConfig.ts
  src/components/Marker/clusterMarker.tsx
  src/components/Marker/pointMarker.tsx
  src/components/mockCafeData.json
  src/container/MapCompContainer.tsx
  src/index.tsx
  src/libs/types/map.ts
  src/libs/utils/checkStringComposedOnlyLetter.ts
  src/libs/utils/renderEmotionElementToHtml.tsx
  src/recoil/map.ts
  src/recoil/testAtom.ts
  src/setupTests.ts
Labels: 기능개발🔥

#25 Refactor: Path 수정 및 Alias 적용 #24
  .eslintignore
  .prettierignore
  config-overrides.js
  package.json
  src/App.tsx
  src/components/ClusterList/index.tsx
  src/components/Filtering/FilterItem.tsx
  src/components/InfoWindow/Contents/Map.tsx
  src/components/InfoWindow/PopUpWindow/index.tsx
  src/components/InfoWindow/index.tsx
  src/components/MapComp/index.tsx
  src/components/Marker/clusterMarker.tsx
  src/containers/MapCompContainer.tsx
  src/index.tsx
  src/libs/apis/getGeoJson.ts
  src/libs/types/infowindow.ts
  src/states/infoWindowState.ts
  src/states/map.ts
  src/states/ui.ts
  tsconfig.json
Labels: 리팩토링🛠️

#22 Refactor: 인포윈도우 스타일링 방식 리펙토링
  src/components/InfoWindow/Contents/Information.tsx
  src/components/InfoWindow/Contents/Map.tsx
  src/components/InfoWindow/Contents/MapButtonList.tsx
  src/components/InfoWindow/Contents/Photoes.tsx
  src/components/InfoWindow/Contents/Tab.tsx
  src/components/InfoWindow/Contents/TabBar.tsx
  src/components/InfoWindow/Contents/Title.tsx
  src/components/InfoWindow/PopUpWindow/style.ts
  src/components/InfoWindow/index.tsx
  src/components/Marker/pointMarker.tsx
  src/constants/barSizes.ts
  src/lib/states/infoWindowState.ts
  src/lib/types/infowindow.ts
Labels: 리팩토링🛠️

#32 Feat: Infowindow UI 수정 반영 #29
  src/components/InfoWindow/Contents/TabBar.tsx
  src/components/InfoWindow/InfoWindow.test.tsx
  src/components/InfoWindow/PopUpWindow/style.ts
  src/components/InfoWindow/index.tsx
  src/constants/popUpHeights.ts
  src/lib/states/infoWindowState.ts
  src/lib/types/infowindow.ts
  src/libs/types/cafe.ts
Labels: 기능개발🔥
